apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq-ecommerce
spec:
  serviceName: rabbitmq-headless-ecommerce
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      containers:
        - name: rabbitmq
          image: rabbitmq:3.13-management
          ports:
            - { name: amqp, containerPort: 5672 }
            - { name: management, containerPort: 15672 }
          env:
            # Nombre del pod para NODENAME (Downward API)
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret-ecommerce
                  key: rabbitmq-username
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret-ecommerce
                  key: rabbitmq-password
            - name: RABBITMQ_ERLANG_COOKIE
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret-ecommerce
                  key: erlang-cookie
            - name: RABBITMQ_USE_LONGNAME
              value: "true"
            - name: RABBITMQ_NODENAME
              value: "rabbit@$(POD_NAME).rabbitmq-headless-ecommerce.ecommerce-dev.svc.cluster.local"
          readinessProbe:
            exec: { command: [ "rabbitmq-diagnostics", "-q", "ping" ] }
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            exec: { command: [ "rabbitmq-diagnostics", "-q", "ping" ] }
            initialDelaySeconds: 20
            periodSeconds: 20
          volumeMounts:
            - name: data
              mountPath: /var/lib/rabbitmq
            - name: config
              mountPath: /etc/rabbitmq/enabled_plugins
              subPath: enabled_plugins
            - name: config
              mountPath: /etc/rabbitmq/rabbitmq.conf
              subPath: rabbitmq.conf
      volumes:
        - name: config
          configMap:
            name: rabbitmq-config-ecommerce
            items:
              - key: enabled_plugins
                path: enabled_plugins
              - key: rabbitmq.conf
                path: rabbitmq.conf
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard
        resources:
          requests:
            storage: 5Gi
