# ConfigMap con variables de entorno para Kafka
# Producción:
# 1. No incluir credenciales aquí (usar Secrets si se usan SASL/SSL).
# 2. Se puede parametrizar vía Helm o Kustomize.
# 3. Algunas variables como `KAFKA_BROKER_ID` pueden sobrescribirse dinámicamente si se usa StatefulSet.

apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config-ecommerce                        # Nombre del ConfigMap
data:
  KAFKA_BROKER_ID: "1"                      # Identificador único del broker
  KAFKA_ZOOKEEPER_CONNECT: "zookeeper-service-ecommerce:2181"   # Dirección del servicio de Zookeeper
  KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9094,DOCKER://0.0.0.0:9093"
#  Lo vamos a manejar en el Stateful
#  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-service-ecommerce:9094,DOCKER://kafka-0.kafka-headless-ecommerce.ecommerce-dev.svc.cluster.local:9093"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,DOCKER:PLAINTEXT"
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
#  Lo vamos a manejar en el Stateful
#  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_INTER_BROKER_LISTENER_NAME: "DOCKER"

