apiVersion: v1
kind: Service
metadata:
  name: kafka-headless-ecommerce
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: kafka
  ports:
    - name: internal
      port: 9093
