apiVersion: v1
kind: Service
metadata:
  name: zookeeper-headless-ecommerce
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: zookeeper
  ports:
    - name: client
      port: 2181 # Aquí se expone el puerto estándar de Zookeeper (2181), que es el que usan los clientes (Kafka, apps, etc.) para conectarse.
