apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper-ecommerce
spec:
  serviceName: zookeeper-headless-ecommerce
  replicas: 1
  selector:
    matchLabels: { app: zookeeper }
  template:
    metadata:
      labels: { app: zookeeper }
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:7.4.0
          ports:
            - { name: client,   containerPort: 2181 }  # clientes
            - { name: peer,     containerPort: 2888 }  # quorum (peers)
            - { name: election, containerPort: 3888 }  # elección de líder
          env:
            - { name: ZOOKEEPER_CLIENT_PORT, value: "2181" }
            - { name: ZOOKEEPER_TICK_TIME,   value: "2000" }
          volumeMounts:
            - { name: data, mountPath: /var/lib/zookeeper/data }
  volumeClaimTemplates:
    - metadata: { name: data }
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard
        resources:
          requests: { storage: 2Gi }
