apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  namespace: ecommerce-dev
spec:
  serviceName: zookeeper-headless
  replicas: 1
  selector:
    matchLabels: { app: zookeeper }
  template:
    metadata:
      labels: { app: zookeeper }
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:7.4.0
          ports: [{ name: client, containerPort: 2181 }]
          env:
            - { name: ZOOKEEPER_CLIENT_PORT, value: "2181" }
            - { name: ZOOKEEPER_TICK_TIME,   value: "2000" }
          volumeMounts:
            - { name: data, mountPath: /var/lib/zookeeper/data }
  volumeClaimTemplates:
    - metadata: { name: data }
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard
        resources:
          requests: { storage: 2Gi }
